import HeaderBox from "@/components/HeaderBox";
import RecentTransactions from "@/components/RecentTransactions";
import RightSidebar from "@/components/RightSidebar";
import TotalBalanceBox from "@/components/TotalBalanceBox";
import { getAccount, getAccounts } from "@/lib/actions/bank.actions";
import { getLoggedInUser } from "@/lib/actions/user.actions";
import React from "react";

const Home = async ({ searchParams: { id, page } }: SearchParamProps) => {
  const currentPage = Number(page as string) || 1; 
  // Converts page param to number from SearchParam since anything in there is a string, finally defaults to page 1.
  const loggedIn = await getLoggedInUser();
  const accounts = await getAccounts({ userId: loggedIn.$id });
  const accountsData = accounts?.data;
  if (!accounts) return; //Exit the function

  console.log({
    loggedIn,
    accounts,
    accountsData
  });

  const appwriteItemId = (id as string) || accountsData[0]?.appwriteItemId;
  //#region Explanation: appwriteItemId & Data Flow
  /*
   * 1. WHAT THIS LINE DOES:
   * It determines which bank account data to display. It first tries to grab the `id` from the URL
   * (e.g., if the user clicked a specific card). If the URL is empty, it safely falls back to
   * grabbing the very first bank account in their list (`accounts?.data[0]`) so the dashboard has a default view.
   *
   * 2. WHAT IS `appwriteItemId`?
   * It is the unique database row ID (document `$id`) generated by the Appwrite database when this
   * bank connection was originally saved. It acts as a safe "claim ticket" for the frontend. The backend
   * uses this ID to securely look up the secret Plaid access token without exposing it to the browser.
   * WHY DO WE NEED THIS?
   * Because the Plaid access token is super sensitive info that can control the user's bank account.
   * We never want to send it to the frontend. So instead, we use `appwriteItemId` as a reference key.
   *
   * 3. WHY THE HELL ARE THERE TWO "data"s???
   * - In `bank.actions.ts` (Backend): `accountsResponse.data`. This is Axios's fault.
   * Axios (the library we use to talk to Plaid) forcefully wraps all API responses inside its own `.data` object. We have no choice but to use it.
   * * - In this file (Frontend): `accounts?.data` is literally the object WE built.
   * On the backend, we packed the accounts array like this: `parseStringify({ data: accounts, ... })`.
   * So basically, because we labeled the box "data" on the server, we gotta use `.data` here to open it back up lol.
   */
  //#endregion
  const account = await getAccount({ appwriteItemId });
  return (
    <section className="home">
      <div className="home-content">
        <header className="home-header">
          <HeaderBox
            type="greeting"
            title="Welcome"
            user={loggedIn?.firstName || "Guest"}
            //#region Why use optional chaining (?.) here?
            // If loggedIn exists → access .firstName
            // If loggedIn is null or undefined → return undefined instead of throwing an error

            // This is used where loggedIn might be null (e.g. user is not authenticated yet, or data is still loading from an API).
            //#endregion
            subtext="This is a subtitle"
          />

          <TotalBalanceBox
            accounts={accountsData}
            totalBanks={accounts?.totalBanks}
            totalCurrentBalance={accounts?.totalCurrentBalance}
          />
        </header>
        <RecentTransactions
          accounts={accountsData}
          transactions={account?.transactions}
          appwriteItemId={appwriteItemId}
          page={currentPage}
        />
      </div>

      <RightSidebar
        user={loggedIn}
        transactions={account?.transactions}
        banks={accountsData.slice(0, 2)}
      />
    </section>
  );
};

export default Home;
